// <auto-generated />
using System;
using LojaCamisasGames.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaCamisasGames.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027225909_InitialMigrationSqlServer")]
    partial class InitialMigrationSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaCamisasGames.Domain.Entities.CamisaGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disponivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Jogo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("CamisasGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "Azul e Branco",
                            DataCadastro = new DateTime(2025, 10, 27, 22, 59, 8, 50, DateTimeKind.Local).AddTicks(1202),
                            Disponivel = true,
                            Jogo = "League of Legends",
                            Nome = "Camisa Oficial Team Liquid 2024",
                            NomeTime = "Team Liquid",
                            Preco = 149.90m,
                            QuantidadeEstoque = 50,
                            Tamanho = "M"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "Preto e Rosa",
                            DataCadastro = new DateTime(2025, 10, 27, 22, 59, 8, 50, DateTimeKind.Local).AddTicks(1208),
                            Disponivel = true,
                            Jogo = "CS:GO",
                            Nome = "Camisa FURIA Esports Home",
                            NomeTime = "FURIA",
                            Preco = 159.90m,
                            QuantidadeEstoque = 30,
                            Tamanho = "G"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "Verde e Branco",
                            DataCadastro = new DateTime(2025, 10, 27, 22, 59, 8, 50, DateTimeKind.Local).AddTicks(1212),
                            Disponivel = true,
                            Jogo = "Valorant",
                            Nome = "Camisa LOUD Champions",
                            NomeTime = "LOUD",
                            Preco = 169.90m,
                            QuantidadeEstoque = 40,
                            Tamanho = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
