// <auto-generated />
using System;
using LojaCamisasGames.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaCamisasGames.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LojaCamisasGames.Domain.Entities.CamisaGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Jogo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CamisasGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "Azul e Branco",
                            DataCadastro = new DateTime(2025, 10, 26, 23, 41, 33, 440, DateTimeKind.Local).AddTicks(2898),
                            Disponivel = true,
                            Jogo = "League of Legends",
                            Nome = "Camisa Oficial Team Liquid 2024",
                            NomeTime = "Team Liquid",
                            Preco = 149.90m,
                            QuantidadeEstoque = 50,
                            Tamanho = "M"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "Preto e Rosa",
                            DataCadastro = new DateTime(2025, 10, 26, 23, 41, 33, 440, DateTimeKind.Local).AddTicks(2903),
                            Disponivel = true,
                            Jogo = "CS:GO",
                            Nome = "Camisa FURIA Esports Home",
                            NomeTime = "FURIA",
                            Preco = 159.90m,
                            QuantidadeEstoque = 30,
                            Tamanho = "G"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "Verde e Branco",
                            DataCadastro = new DateTime(2025, 10, 26, 23, 41, 33, 440, DateTimeKind.Local).AddTicks(2907),
                            Disponivel = true,
                            Jogo = "Valorant",
                            Nome = "Camisa LOUD Champions",
                            NomeTime = "LOUD",
                            Preco = 169.90m,
                            QuantidadeEstoque = 40,
                            Tamanho = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
